# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/processor/processor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor || ORIG_REF_NAME==processor}]

# IP: bd/processor/ip/processor_clk_wiz_0_0/processor_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_clk_wiz_0_0 || ORIG_REF_NAME==processor_clk_wiz_0_0}]

# IP: bd/processor/ip/processor_axi_uartlite_0_0/processor_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_uartlite_0_0 || ORIG_REF_NAME==processor_axi_uartlite_0_0}]

# IP: bd/processor/ip/processor_axi_gpio_0_0/processor_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_gpio_0_0 || ORIG_REF_NAME==processor_axi_gpio_0_0}]

# IP: bd/processor/ip/processor_microblaze_0_2/processor_microblaze_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_microblaze_0_2 || ORIG_REF_NAME==processor_microblaze_0_2}]

# IP: bd/processor/ip/processor_mdm_1_2/processor_mdm_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_mdm_1_2 || ORIG_REF_NAME==processor_mdm_1_2}]

# IP: bd/processor/ip/processor_rst_clk_wiz_0_100M_2/processor_rst_clk_wiz_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_rst_clk_wiz_0_100M_2 || ORIG_REF_NAME==processor_rst_clk_wiz_0_100M_2}]

# IP: bd/processor/ip/processor_microblaze_0_axi_periph_0/processor_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_microblaze_0_axi_periph_0 || ORIG_REF_NAME==processor_microblaze_0_axi_periph_0}]

# IP: bd/processor/ip/processor_mig_7series_0_2/processor_mig_7series_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_mig_7series_0_2 || ORIG_REF_NAME==processor_mig_7series_0_2}]

# IP: bd/processor/ip/processor_axi_smc_0/processor_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_axi_smc_0 || ORIG_REF_NAME==processor_axi_smc_0}]

# Block Designs: bd/processor/ip/processor_axi_smc_0/bd_0/bd_4f79.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_13/bd_4f79_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_22/bd_4f79_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_25/bd_4f79_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_31/bd_4f79_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_26/bd_4f79_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_27/bd_4f79_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_28/bd_4f79_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_29/bd_4f79_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_30/bd_4f79_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_23/bd_4f79_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_24/bd_4f79_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_19/bd_4f79_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_20/bd_4f79_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_21/bd_4f79_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_14/bd_4f79_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_15/bd_4f79_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_16/bd_4f79_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_17/bd_4f79_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_18/bd_4f79_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_10/bd_4f79_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_11/bd_4f79_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_12/bd_4f79_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_5/bd_4f79_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_6/bd_4f79_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_7/bd_4f79_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_8/bd_4f79_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_9/bd_4f79_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_0/bd_4f79_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_1/bd_4f79_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_2/bd_4f79_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_3/bd_4f79_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_4/bd_4f79_psr_aclk2_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/processor/ip/processor_rst_mig_7series_0_81M_0/processor_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==processor_rst_mig_7series_0_81M_0}]

# IP: bd/processor/ip/processor_PmodSD_0_0/processor_PmodSD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_PmodSD_0_0 || ORIG_REF_NAME==processor_PmodSD_0_0}]

# IP: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodSD_axi_gpio_0_0 || ORIG_REF_NAME==PmodSD_axi_gpio_0_0}]

# IP: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodSD_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodSD_axi_quad_spi_0_0}]

# IP: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodSD_pmod_bridge_0_0 || ORIG_REF_NAME==PmodSD_pmod_bridge_0_0}]

# IP: bd/processor/ip/processor_xbar_0/processor_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_xbar_0 || ORIG_REF_NAME==processor_xbar_0}]

# IP: bd/processor/ip/processor_dlmb_v10_2/processor_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_dlmb_v10_2 || ORIG_REF_NAME==processor_dlmb_v10_2}]

# IP: bd/processor/ip/processor_ilmb_v10_2/processor_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_ilmb_v10_2 || ORIG_REF_NAME==processor_ilmb_v10_2}]

# IP: bd/processor/ip/processor_dlmb_bram_if_cntlr_2/processor_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==processor_dlmb_bram_if_cntlr_2}]

# IP: bd/processor/ip/processor_ilmb_bram_if_cntlr_2/processor_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==processor_ilmb_bram_if_cntlr_2}]

# IP: bd/processor/ip/processor_lmb_bram_2/processor_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_lmb_bram_2 || ORIG_REF_NAME==processor_lmb_bram_2}]

# IP: bd/processor/ip/processor_PAMChunkSearch_0_0/processor_PAMChunkSearch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_PAMChunkSearch_0_0 || ORIG_REF_NAME==processor_PAMChunkSearch_0_0}]

# IP: bd/processor/ip/processor_offTargetSearcher_0_1/processor_offTargetSearcher_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_offTargetSearcher_0_1 || ORIG_REF_NAME==processor_offTargetSearcher_0_1}]

# XDC: bd/processor/ip/processor_clk_wiz_0_0/processor_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_clk_wiz_0_0 || ORIG_REF_NAME==processor_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/processor/ip/processor_clk_wiz_0_0/processor_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_clk_wiz_0_0 || ORIG_REF_NAME==processor_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/processor/ip/processor_clk_wiz_0_0/processor_clk_wiz_0_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_uartlite_0_0/processor_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_axi_uartlite_0_0 || ORIG_REF_NAME==processor_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_axi_uartlite_0_0/processor_axi_uartlite_0_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_uartlite_0_0/processor_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_axi_uartlite_0_0 || ORIG_REF_NAME==processor_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_axi_gpio_0_0/processor_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_axi_gpio_0_0 || ORIG_REF_NAME==processor_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_axi_gpio_0_0/processor_axi_gpio_0_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_gpio_0_0/processor_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_axi_gpio_0_0 || ORIG_REF_NAME==processor_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_microblaze_0_2/processor_microblaze_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_microblaze_0_2 || ORIG_REF_NAME==processor_microblaze_0_2}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_microblaze_0_2/processor_microblaze_0_2_ooc_debug.xdc

# XDC: bd/processor/ip/processor_microblaze_0_2/processor_microblaze_0_2_ooc.xdc

# XDC: bd/processor/ip/processor_mdm_1_2/processor_mdm_1_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_mdm_1_2 || ORIG_REF_NAME==processor_mdm_1_2}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_mdm_1_2/processor_mdm_1_2_ooc_trace.xdc

# XDC: bd/processor/ip/processor_rst_clk_wiz_0_100M_2/processor_rst_clk_wiz_0_100M_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_rst_clk_wiz_0_100M_2 || ORIG_REF_NAME==processor_rst_clk_wiz_0_100M_2}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_rst_clk_wiz_0_100M_2/processor_rst_clk_wiz_0_100M_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_rst_clk_wiz_0_100M_2 || ORIG_REF_NAME==processor_rst_clk_wiz_0_100M_2}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_rst_clk_wiz_0_100M_2/processor_rst_clk_wiz_0_100M_2_ooc.xdc

# XDC: bd/processor/ip/processor_mig_7series_0_2/processor_mig_7series_0_2/user_design/constraints/processor_mig_7series_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_mig_7series_0_2 || ORIG_REF_NAME==processor_mig_7series_0_2}]

# XDC: bd/processor/ip/processor_mig_7series_0_2/processor_mig_7series_0_2/user_design/constraints/processor_mig_7series_0_2_ooc.xdc

# XDC: bd/processor/ip/processor_mig_7series_0_2/processor_mig_7series_0_2_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processor_mig_7series_0_2 || ORIG_REF_NAME==processor_mig_7series_0_2}]

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_13/bd_4f79_s00a2s_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_22/bd_4f79_s01a2s_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_25/bd_4f79_m00s2a_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_26/bd_4f79_m00arn_0/bd_4f79_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_26/bd_4f79_m00arn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_27/bd_4f79_m00rn_0/bd_4f79_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_27/bd_4f79_m00rn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_28/bd_4f79_m00awn_0/bd_4f79_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_28/bd_4f79_m00awn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_29/bd_4f79_m00wn_0/bd_4f79_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_29/bd_4f79_m00wn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_30/bd_4f79_m00bn_0/bd_4f79_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_30/bd_4f79_m00bn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_23/bd_4f79_sarn_1_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_24/bd_4f79_srn_1_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_14/bd_4f79_sarn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_15/bd_4f79_srn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_16/bd_4f79_sawn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_17/bd_4f79_swn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_18/bd_4f79_sbn_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_5/bd_4f79_arsw_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_6/bd_4f79_rsw_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_7/bd_4f79_awsw_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_8/bd_4f79_wsw_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_9/bd_4f79_bsw_0_ooc.xdc

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_1/bd_4f79_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_1/bd_4f79_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_2/bd_4f79_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_2/bd_4f79_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_3/bd_4f79_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_3/bd_4f79_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_4/bd_4f79_psr_aclk2_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/bd_0/ip/ip_4/bd_4f79_psr_aclk2_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/processor/ip/processor_axi_smc_0/ooc.xdc

# XDC: bd/processor/ip/processor_rst_mig_7series_0_81M_0/processor_rst_mig_7series_0_81M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==processor_rst_mig_7series_0_81M_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_rst_mig_7series_0_81M_0/processor_rst_mig_7series_0_81M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==processor_rst_mig_7series_0_81M_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_rst_mig_7series_0_81M_0/processor_rst_mig_7series_0_81M_0_ooc.xdc

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_gpio_0_0 || ORIG_REF_NAME==PmodSD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_ooc.xdc

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_gpio_0_0 || ORIG_REF_NAME==PmodSD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodSD_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodSD_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodSD_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_pmod_bridge_0_0 || ORIG_REF_NAME==PmodSD_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/processor/ip/processor_PmodSD_0_0/processor_PmodSD_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_PmodSD_0_0 || ORIG_REF_NAME==processor_PmodSD_0_0}] {/inst }]/inst ]]

# XDC: bd/processor/ip/processor_PmodSD_0_0/src/PmodSD_ooc.xdc

# XDC: bd/processor/ip/processor_xbar_0/processor_xbar_0_ooc.xdc

# XDC: bd/processor/ip/processor_dlmb_v10_2/processor_dlmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_dlmb_v10_2 || ORIG_REF_NAME==processor_dlmb_v10_2}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_dlmb_v10_2/processor_dlmb_v10_2_ooc.xdc

# XDC: bd/processor/ip/processor_ilmb_v10_2/processor_ilmb_v10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processor_ilmb_v10_2 || ORIG_REF_NAME==processor_ilmb_v10_2}] {/U0 }]/U0 ]]

# XDC: bd/processor/ip/processor_ilmb_v10_2/processor_ilmb_v10_2_ooc.xdc

# XDC: bd/processor/ip/processor_dlmb_bram_if_cntlr_2/processor_dlmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/processor/ip/processor_ilmb_bram_if_cntlr_2/processor_ilmb_bram_if_cntlr_2_ooc.xdc

# XDC: bd/processor/ip/processor_lmb_bram_2/processor_lmb_bram_2_ooc.xdc

# XDC: bd/processor/processor_ooc.xdc
